### ISSUE TITLE
Review and implement privacy by design

### ISSUE THREAD

**Issue by MaxGitHubAccount** [gematik/api-erp#8]
Thanks for open-sourcing the app and interface documentation.
I am posting here because I cannot open an issue here https://github.com/gematik/api-erp.

Unfortunately, the functional and technical design and implementation is now already in place, which means that reworking basic design decisions is now time-consuming and costly. It would be good if this was recorded in a lessons learnt register to management for future decisions.

Patient data is the most intimate of our data. This requires the highest security and data protection requirements on the system not only by the GDPR but also for acceptance. The current design is for prescriptions for insured persons to be stored entirely at Gematik. https://github.com/gematik/api-erp/blob/master/docs/erp_versicherte.adoc#anwendungsf%C3%A4lle-e-rezept-als-versicherter-verwalten

This entails great risks, which would not necessarily have to be taken. It would be conceivable, for example, that prescriptions are signed by Gematik when they are written (it would be even better if doctors had their own expiring, revocable keys, which in turn would be issued by a Gematik CA), but then not stored centrally but on the customer's device. As soon as the patient brings his prescription to a pharmacy, the authenticity of the prescription is checked via the signature and only one transaction is stored for redeeming and thus invalidating the prescription. This does not require any personal or prescription-related data to be stored, collected or processed.
The argument that prescriptions could be lost in this way does not apply here, as patients can also lose the printout or their Access_Token in the current solution.

My proposed solution is probably not state of the art. However, it would be good if the whole workflow could be reviewed with data protection experts on privacy by design and revised accordingly. Currently, the implementation means a significant unnecessary deterioration in the level of data protection of prescriptions.

**Comment by HendrikGematik** [comment]
As mentioned above, the e-prescription system has to enforce a workflow and validation of data and its signature. This is cannot be done with an end-to-end-encryption. To ensure privacy, integrity and avaliability the e-prescription server implements a trusted execution environment (TEE) that we call "VAU"-concept.

**Comment by MaxGitHubAccount** [comment]
Hi @HendrikGematik ,

thanks for your response. I also apologise for the rough answer which was given before (not by me), which I also can understand as if this data goes into wrong hands terrible things can happen - not even necessary in bad faith, could also happen via a not yet known security flaw (like log4j), so any data which isnt there in the first place is better (Datensparsamkeit). I honestly want this system as good as possible and made the effort to read the API-documentation. Could you please document or publish here (or link if I missed it) how you minimized data which could not be saved end-to-end and why? I am asking because e.g. for an email or n:n-video-chats there is end-to-end-encryption possible also ensuring signatures etc and I wonder why it isnt here and if it truly isnt possible that at least everything which could be hidden from the central server is hidden via e2ee as there is also no reason for any other data gathering (Zweckmäßigkeit).
It would be very kind if you could work with us instead of closing the issue which feels to me more like working against us.

**Comment by HendrikGematik** [comment]
@MaxGitHubAccount 

Sorry to disappoint, this is not a matter of "with" or "against". You may trust the force. You may also accept, that there are workflows, that need to evaluate data in a serverside backend. In the ePrescription, data is minimized by design. As you can see for example in https://simplifier.net/erezept every object is minimized to the data that is needed for the process. And also, KBV, DAV and GKV name the purpose of each object's attribute in their technical appendixes to the Bundesmantelvertrag and related §§ in SGBV. 
https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/apotheken/technische_anlagen_aktuell/TA7_001_20210610.pdf
https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/apotheken/technische_anlagen_aktuell/TA7_Anhang1_001_20210610_Mapping.pdf
https://update.kbv.de/ita-update/DigitaleMuster/ERP/KBV_ITA_VGEX_Technische_Anlage_ERP.pdf

Did you ever asked how your data is handled and protected outside the eHealth Telematikinfrastruktur?

I closed this issue, because any changes to this API description won't change the security architecture at all.

Best wishes for a merry christmas. Stay safe.

Hendrik

**Comment by MaxGitHubAccount** [comment]
Thanks for your response Hendrik. I will review your posts in time :-)

I also wish you and your family a wonderful christmas!
